# Compile stage
FROM golang:stretch AS build-env

ADD . /dockerdev
WORKDIR /dockerdev/cmd

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o gluster-simple-csi-plugin

# Final stage
FROM mvallim/gluster-debian:7-stretch-server

LABEL maintainers="Marcos Vallim <tischer@gmail.com>"
LABEL description="GlusterFS Simple Driver Provisioner"

ENV NODE_ID=""
ENV CSI_ENDPOINT=""

RUN apt-get install -y thin-provisioning-tools lvm2 acl xfsprogs && apt-get clean
COPY --from=build-env /dockerdev/cmd/gluster-simple-csi-plugin /bin/

ENTRYPOINT ["/bin/gluster-simple-csi-plugin"]