FROM mvallim/gluster-debian:7-stretch-server

LABEL maintainers="Marcos Vallim <tischer@gmail.com>"
LABEL description="GlusterFS Simple Driver Provisioner"

ENV NODE_ID=""
ENV CSI_ENDPOINT=""

RUN apt-get install -y acl && apt-get clean

ADD gluster-simple-csi-plugin /bin/

ENTRYPOINT ["/bin/gluster-simple-csi-plugin"]